- .github/workflows/ci.yml
- reqwest-tracing/Cargo.toml
- reqwest-tracing/README.md
- reqwest-tracing/src/lib.rs
- reqwest-tracing/src/middleware.rs
- reqwest-tracing/src/otel.rs
> Add support for OpenTelemetry 0.16 and tracing-opentelemetry 0.15

- README.md
- reqwest-middleware/Cargo.toml
- reqwest-middleware/src/client.rs
- reqwest-middleware/src/lib.rs
- reqwest-middleware/src/middleware.rs
- reqwest-retry/CHANGELOG.md
- reqwest-retry/README.md
- reqwest-retry/src/lib.rs
- reqwest-tracing/README.md
- reqwest-tracing/src/lib.rs
> Include README in crate doctests and improve documentation

- reqwest-tracing/Cargo.toml
- reqwest-tracing/README.md
- reqwest-tracing/src/lib.rs
- reqwest-tracing/src/middleware.rs
- reqwest-tracing/src/otel.rs
fix #28 
not finished yet, we need to wait for the release of tracing-opentelemetry
> update to opentelemetry 0.17

- .cargo/audit.toml
This should fix the security step in CI that was discussed in #29
> allow RUSTSEC-2020-0159

- CHANGELOG.md
- reqwest-middleware/Cargo.toml
- reqwest-retry/CHANGELOG.md
- reqwest-retry/Cargo.toml
- reqwest-tracing/CHANGELOG.md
- reqwest-tracing/Cargo.toml
Dev version bumps after releasing 0.1.5.
> Release reqwest middleware 0.1.5

- reqwest-tracing/Cargo.toml
- reqwest-tracing/src/middleware.rs
- reqwest-tracing/src/otel.rs
There are a few references to OpenTracing that I've corrected to OpenTelemetry. Nothing too significant.
This is a minimal change that doesn't change functionality or fix bugs, so I didn't add a `CHANGELOG` entry for it.
> chore: correct OpenTracing -> OpenTelemetry

- reqwest-tracing/README.md
> docs: fix readme

- reqwest-retry/src/middleware.rs
I was reading code out of curiosity (as I often do in the evenings) and I noticed this async recursion hack that seemed unnecessary. With a few tweaks I've made it simply iterative which reduces some unnecessary overhead
> fix recursion in retry

- CHANGELOG.md
- reqwest-middleware/src/client.rs
Same as https://github.com/TrueLayer/reqwest-middleware/pull/22 but for `RequestBuilder`
> Add implementation of Debug trait for RequestBuilder.

- CHANGELOG.md
- reqwest-tracing/CHANGELOG.md
> bump reqwest-tracing

- reqwest-tracing/src/lib.rs
- reqwest-tracing/src/reqwest_otel_span_macro.rs
> Make clear examples are just examples

- reqwest-tracing/src/reqwest_otel_span_builder.rs
- reqwest-tracing/src/reqwest_otel_span_macro.rs
Fixes clippy on 1.65, which is used in CI.
> Fix main builds

- reqwest-tracing/CHANGELOG.md
- reqwest-tracing/src/lib.rs
- reqwest-tracing/src/reqwest_otel_span_builder.rs
- reqwest-tracing/src/reqwest_otel_span_macro.rs
captures the request URL to the canonical attribute for this.
> Capture URL as http.url

- reqwest-tracing/CHANGELOG.md
> Fix indents in Changelog.

- CHANGELOG.md
- reqwest-middleware/Cargo.toml
- reqwest-middleware/src/middleware.rs
- reqwest-retry/CHANGELOG.md
- reqwest-retry/Cargo.toml
- reqwest-tracing/CHANGELOG.md
- reqwest-tracing/Cargo.toml
> bump all versions

- reqwest-tracing/README.md
README example now fails to build.
> Update example in tracing README

- .gitignore
- CHANGELOG.md
- reqwest-middleware/src/error.rs
> Impl reqwest::Error methods

- reqwest-retry/CHANGELOG.md
- reqwest-retry/Cargo.toml
We never published #33 from May
> [reqwest-retry] Patch release v0.2.3

- .github/workflows/ci.yml
- reqwest-tracing/Cargo.toml
- reqwest-tracing/README.md
- reqwest-tracing/src/lib.rs
- reqwest-tracing/src/middleware.rs
- reqwest-tracing/src/otel.rs
Also adds corresponding `tracing-opentelemetry` version `0.22`
> Add support for `opentelemetry` version `0.21`

- reqwest-tracing/Cargo.toml
- reqwest-tracing/src/otel.rs
Missed in https://github.com/TrueLayer/reqwest-middleware/pull/118
> fix(reqwest-tracing): fix missing deps

- CHANGELOG.md
- reqwest-tracing/Cargo.toml
- reqwest-tracing/src/reqwest_otel_span_builder.rs
A copy of #134 but just with the matchit upgrade.
Thank you @matiu2 for raising the original PR
> feat!: upgrade to matchit `0.8.0`

- CHANGELOG.md
for #144
will edit the release object if accepted
> Document breaking feature removal for reqwest-middleware

- reqwest-retry/src/lib.rs
> add re-exports from retry-policies crate

- reqwest-retry/CHANGELOG.md
- reqwest-retry/Cargo.toml
- reqwest-retry/src/middleware.rs
Bumped retry policies to 0.4 and made the necessary code changes (swapping to SystemTime) associated with it.
Fixes #154
> Bump retry-policies to 0.4

- CHANGELOG.md
- reqwest-middleware/Cargo.toml
- reqwest-retry/CHANGELOG.md
- reqwest-retry/Cargo.toml
- reqwest-tracing/CHANGELOG.md
- reqwest-tracing/Cargo.toml
fixes #164
I'm sorry for this release taking a long time.
I want to give a special thanks to @cbeck88 for continuing to provide high-quality code reviews for many of the recent PRs on this repository. This has been very valuable.
> chore: prepare release 🚀 

- reqwest-middleware/CHANGELOG.md
- reqwest-middleware/Cargo.toml
- reqwest-retry/CHANGELOG.md
- reqwest-retry/Cargo.toml
- reqwest-tracing/CHANGELOG.md
- reqwest-tracing/Cargo.toml
Prepare release of:
- reqwest-middleware 0.3.2 -> 0.3.3
- reqwest-tracing 0.5.2 -> 0.5.3
- reqwest-retry 0.6.0 -> 0.6.1
> chore: prepare release :rocket:

- reqwest-tracing/README.md
Fixed the example in the `README.md`, I made an (somewhat) educated guess on how to wire up stdout, but the output didn't match the original output at all so maybe things have changed.
I assume that a simple change to the `README.md` doesn't need a changelog entry.
> the example in the readme didn't compile

- reqwest-tracing/CHANGELOG.md
- reqwest-tracing/Cargo.toml
- reqwest-tracing/src/lib.rs
- reqwest-tracing/src/middleware.rs
- reqwest-tracing/src/otel.rs
~Waiting for https://github.com/tokio-rs/tracing-opentelemetry/pull/184~ now released
> feat: support OTel 0.27

- reqwest-tracing/CHANGELOG.md
- reqwest-tracing/Cargo.toml
- reqwest-tracing/src/lib.rs
- reqwest-tracing/src/middleware.rs
- reqwest-tracing/src/otel.rs
> feat: support OTel 0.28

- reqwest-middleware/CHANGELOG.md
- reqwest-middleware/Cargo.toml
- reqwest-tracing/CHANGELOG.md
- reqwest-tracing/Cargo.toml
fixes #220
https://github.com/TrueLayer/reqwest-middleware/pull/215#issuecomment-2676373177
> chore: bump versions for release

- reqwest-tracing/CHANGELOG.md
- reqwest-tracing/Cargo.toml
- reqwest-tracing/src/lib.rs
- reqwest-tracing/src/middleware.rs
- reqwest-tracing/src/otel.rs
> feat: support OpenTelemetry 0.29
