CHANGELOG.md
reqwest-middleware/src/client.rs

Adds `ClientWithMiddleware::execute_with_extensions` and `RequestBuilder::send_with_extensions`.
Closes #1

Add (send/execute)_with_extensions

---

CHANGELOG.md
reqwest-middleware/Cargo.toml
reqwest-retry/CHANGELOG.md
reqwest-retry/Cargo.toml
reqwest-tracing/CHANGELOG.md
reqwest-tracing/Cargo.toml

Similar to #6 but it's slightly less intrusive. Disabled default features for reqwest entirely so that the consumer of these crates can decided explicitly what features to enable. It's expected that they include the `reqwest` crate in their own dependency anyway (needed to create the `ClientWithMiddleware`) so they will likely have the default dependencies enabled on their own

Reqwest default features

---

reqwest-tracing/Cargo.toml
reqwest-tracing/src/otel.rs

fix #17 
this update requires moving to tracing-subscriber 0.3. It removes chrono
from transitive dependencies, following
https://rustsec.org/advisories/RUSTSEC-2020-0159.html
Context:
- tracing-opentelemetry 0.16 release: https://github.com/tokio-rs/tracing/pull/1682
- tracing subscriber 0.3 release with the removal of chrono: https://github.com/tokio-rs/tracing/pull/1677

update tracing-opentelemetry to 0.16

---

reqwest-middleware/src/client.rs

This adds a implementation of Debug that skips the middleware_stack field to avoid breaking changes, described [here](https://github.com/TrueLayer/reqwest-middleware/pull/21#issuecomment-986632499) in PR #21

adds manual Debug implementation for ClientWithMiddleware

---

reqwest-middleware/src/client.rs

This moves from the finish() method to the finish_non_exhaustive() method in the custom Debug impl for ClientWithMiddleware.
"Marks the struct as non-exhaustive, indicating to the reader that there are some other fields that are not shown in the debug representation." - [`DebugStruct` docs](https://doc.rust-lang.org/stable/std/fmt/struct.DebugStruct.html#method.finish_non_exhaustive)

moved to finish_non_exhaustive in Debug impl for ClientWithMiddleware

---

.github/workflows/ci.yml
reqwest-tracing/Cargo.toml
reqwest-tracing/src/middleware.rs
reqwest-tracing/src/otel.rs

I noticed how the request_span was never 'entered'. My gut instinct tells me this is a mistake and that it should be.
This then solves the second issue (#37) where the span isn't always enabled for the propagation, by using the current span always.

fix: context not propagated if request_span is disabled

---

reqwest-tracing/CHANGELOG.md
reqwest-tracing/src/middleware.rs

I may have misunderstood the intention of the existing implementation, but I think this is more aligned with [what the semantic conventions specify](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#status).

Update `otel.status_code` mapping with latest version of spec.

---

reqwest-middleware/Cargo.toml
reqwest-retry/Cargo.toml
reqwest-tracing/CHANGELOG.md
reqwest-tracing/Cargo.toml

bumps libs releasing changes to  reqwest-tracing:
- Fix how we set the OpenTelemetry span status, based on the HTTP response status.

bump reqwest-tracing to v0.2.3

---

reqwest-retry/src/middleware.rs

Prompted by #44, added docs about `RetryTransientMiddleware` not supporting streaming requests

Add note about streaming requests in RetryTransientMiddleware docs

---

reqwest-tracing/README.md

Just add the missing `task-local-extensions` dependency that are required to run the code in the README.

Add missing dep in reqwest-tracing README

---

reqwest-middleware/src/client.rs

try_clone moves self and effectively destroy it which defeats the purpose of cloning. It should instead borrow self and also clone the client inside it and return a new RequestBuilder.

Borrow self when try_clone and clone inner client.

---

reqwest-retry/CHANGELOG.md
reqwest-retry/Cargo.toml
reqwest-retry/src/retryable.rs
reqwest-retry/tests/all/helpers/simple_server.rs
reqwest-retry/tests/all/retry.rs

Tries to downcast the hyper error in order to classify the underlying io::Error when the hyper::ErrorKind is IO.
This allows us to catch when we get `Connection reset by peer` and retry it.

feat: classify io error connection reset by peer

---

reqwest-retry/src/middleware.rs
reqwest-retry/tests/all/retry.rs

Removed retry limit:
- Remove MAXIMUM_NUMBER_OF_RETRIES metadata and references in middleware.rs
- Correct mispelling: retry_decision to retry_decision in middleware.rs
- Update Retryable matching to only match Retryable::Transient in middleware.rs
- Simplify branching by removing n_past_retries < MAXIMUM_NUMBER_OF_RETRIES condition in middleware.rs

fix: remove middleware retry limit

---

CHANGELOG.md
reqwest-tracing/Cargo.toml
reqwest-tracing/src/lib.rs
reqwest-tracing/src/reqwest_otel_span_builder.rs

- If this extension is provided span names will be `<method> <path name>`. These path names will include parameter names rather than IDs or other elements that would increase the cardinality.
- The default span name has been update to the HTTP method name rather than `reqwest-http-client` which feels closer to [the otel spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#name).

Add `OtelPathNames` for span names

---

reqwest-middleware/src/client.rs

Addresses an issue where the Http version of a request cannot be changed when using reqwest_middleware.

Added version function to RequestBuilder impl

---

CHANGELOG.md
reqwest-tracing/CHANGELOG.md
reqwest-tracing/Cargo.toml

The changes were added to the reqwest-middleware change log but are in reqwest-tracing. This moves them to the unreleased reqwest-tracing changes.

Move path matching changes to right log

---

reqwest-retry/CHANGELOG.md
reqwest-retry/src/lib.rs
reqwest-retry/src/middleware.rs
reqwest-retry/src/retryable.rs
reqwest-retry/src/retryable_strategy.rs

Added functionality that allows you to specify custom functions that will direct whether a request will be retried or not. 
The implementation doesn't interfere with the already existing API. 
A `RetryableStrategy` trait, much like the `SpanBackend` trait for `TracingMiddleware`.
Default handlers are added for both success and error. (those are the results of splitting the original `Retryable::from_reqwest_response` function)
Added a function `new_with_policy_and_strategy` on `RetryTransientMiddleware` that takes a `RetryableStrategy` which will be used to decide whether a request should be retried.

Added a way to specify custom functions which decide whether a request should be retried or not

---

.github/workflows/ci.yml
reqwest-tracing/CHANGELOG.md
reqwest-tracing/Cargo.toml
reqwest-tracing/src/lib.rs
reqwest-tracing/src/middleware.rs
reqwest-tracing/src/otel.rs
reqwest-tracing/src/reqwest_otel_span_builder.rs

Some HTTP clients want to be traced, but do not want to propagate the opentelemetry contexts. Adding the `DisableOtelPropagation` extension will disable the propagation functionality
A future breaking change: split tracing and telemetry propagation into 2 middlewares.
Also drive-by fixed #85

disable context propagation

---

.github/workflows/ci.yml
reqwest-tracing/Cargo.toml
reqwest-tracing/src/lib.rs
reqwest-tracing/src/middleware.rs
reqwest-tracing/src/otel.rs

Some features were removed in opentelemetry 0.20 and moved into separate crates, it only seems to effect tests though. No harm done.
The opentelemtry github repo suggests that they are releasing opentelemetry 1.0.0 shortly, I'd recommend removing all features and releasing a breaking change with the old versions removed once that happens

add opentelementry 0.20 support

---

.github/workflows/ci.yml
README.md

Wasm tests have been unmaintained and broken for a while. We don't use it so we have no motivation to update them, I removed the tests and added a warning that the crates may or may not work with wasm.

Disable wasm tests and add warning to README

---

reqwest-retry/CHANGELOG.md
reqwest-retry/Cargo.toml
reqwest-retry/tests/all/retry.rs

Backwards-incompatible because this forces clients to also upgrade `retry-policies`.

[EWT-319] Upgrade retry-policies

---

CHANGELOG.md
reqwest-middleware/Cargo.toml
reqwest-middleware/src/client.rs

This adds the `fetch_mode_no_cors` method which is available in `reqwest::RequestBuilder` but currently not in `reqwest_middleware::RequestBuilder`.

add fetch_mode_no_cors_method

---

reqwest-retry/src/middleware.rs

Document that sleeps happen with `tokio::time::sleep` if anyone wants to run it in time-stepped environment (some unit test or something).
N/A

Document using `tokio::time::sleep`

---

reqwest-retry/Cargo.toml
reqwest-retry/src/middleware.rs

This PR adapts to the changes made in `retry-policies` [here](https://github.com/TrueLayer/retry-policies/pull/16).  ~It will be updated with the new `retry-policies` version if/when that goes in~ (done).

Adapt to retry-policies changes

---

.github/workflows/ci.yml
reqwest-tracing/Cargo.toml
reqwest-tracing/README.md
reqwest-tracing/src/lib.rs
reqwest-tracing/src/middleware.rs
reqwest-tracing/src/otel.rs

Opentelemetry 0.22 is released.
Once https://github.com/tokio-rs/tracing-opentelemetry/pull/100 
is into a release (presumably 0.23), then this PR should pass CI and be mergable.

Support opentelemetry 0.22

---

CHANGELOG.md
reqwest-middleware/Cargo.toml

The minimum version of reqwest `0.11.4` is no longer true after 0.2.3 release
- Added all `reqwest::Error` methods for `reqwest_middleware::Error`
methods url_mut, with_url, without_url were added after `0.11.10`

Update reqwest version to 0.11.10

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
reqwest-middleware/Cargo.toml
reqwest-middleware/src/client.rs
reqwest-middleware/src/lib.rs
reqwest-middleware/src/middleware.rs
reqwest-middleware/src/req_init.rs
reqwest-retry/CHANGELOG.md
reqwest-retry/Cargo.toml
reqwest-retry/src/middleware.rs
reqwest-retry/src/retryable_strategy.rs
reqwest-tracing/CHANGELOG.md
reqwest-tracing/Cargo.toml
reqwest-tracing/README.md
reqwest-tracing/src/lib.rs
reqwest-tracing/src/middleware.rs
reqwest-tracing/src/otel.rs
reqwest-tracing/src/reqwest_otel_span_builder.rs
reqwest-tracing/src/reqwest_otel_span_macro.rs

reqwest 0.12 update necessarily causes a major version change here. Might as well break more things while we're at it
- update reqwest and http crates
- remove task_local_extensions in favour of http::Extensions
- remove older opentelemetry packages (over 1 year old)
- make otel features additive

reqwest 0.12 and other breaking changes

---

CHANGELOG.md
reqwest-middleware/src/client.rs
reqwest-middleware/src/middleware.rs

fixes #139
related https://github.com/TrueLayer/reqwest-middleware/pull/135
There are other potential long term solutions listed [here](https://github.com/TrueLayer/reqwest-middleware/issues/139#issuecomment-2045946644)
> I didn't put much thought into it. Internally there used to be a `Box<[Arc<dyn Middleware>]>` which is cloned about quite often.
>
> * https://docs.rs/reqwest-middleware/0.2.5/src/reqwest_middleware/client.rs.html#87
> * https://docs.rs/reqwest-middleware/0.2.5/src/reqwest_middleware/client.rs.html#139
>
> Because of all the cloning, I decided to flip it to be `Arc<Box>` instead of `Box<Arc>`.
>
> I see three solutions here.
>
> 1. The one I'd lean towards is `Arc<Arc>` even if it's a bit silly, but prevents extra unnecessary allocations on each request.
> 2. An …

chore: revert change switching from `Arc` to `Box` in public APIs

---

reqwest-retry/CHANGELOG.md
reqwest-retry/src/middleware.rs

Allow changing the log level for the retry event.

feat(reqwest-retry): Configurable log level for retry event

---

reqwest-tracing/src/reqwest_otel_span_macro.rs

`reqwest` is case-insensitive when it comes to headers, but `-` doesn't get replaced with a `_`.

Fix logging of `User-Agent` header in `reqwest-tracing`

---

reqwest-middleware/src/client.rs

This pull request adds a new `extend` function to the `ClientBuilder` which takes a `ClientWithMiddleware` instance and appends its middleware and initialiser stacks to the `ClientBuilder` instance it's being called on.
This is very convenient when `reqwest_middleware` is being used on libraries that accept a `ClientWithMiddleware`, but need to append their own middlewares to the client that's being passed down from the app.

[BOT-272] ClientBuilder extend convenience function

---

.github/workflows/ci.yml
CHANGELOG.md
reqwest-tracing/Cargo.toml
reqwest-tracing/src/lib.rs
reqwest-tracing/src/middleware.rs
reqwest-tracing/src/otel.rs

Added support for the 0.23 series of OpenTelemetry crates.

feat: support opentelemetry 0.23

---

CHANGELOG.md
reqwest-middleware/Cargo.toml

Add `rustls-tls`, `http2`, and `charset` features, which pass through to `reqwest`.

Expose some more reqwest features

---

CHANGELOG.md
reqwest-middleware/src/lib.rs

In a large project, it's not unheard of for multiple mutually-incompatible versions of a major crate like `reqwest` to end up in the mix.  By re-exporting the version of `reqwest` used by `reqwest-middleware`, we can be sure we're referring to the *correct* `reqwest`, rather than some other, incompatible, `reqwest`.

Re-export reqwest crate

---

reqwest-tracing/CHANGELOG.md
reqwest-tracing/Cargo.toml
reqwest-tracing/src/lib.rs
reqwest-tracing/src/reqwest_otel_span_builder.rs
reqwest-tracing/src/reqwest_otel_span_macro.rs

This PR introduces a feature flag to `reqwest-middleware` that enables the old field names along with the new ones.

Add feature flag for deprecated fields

---

reqwest-retry/Cargo.toml

`chrono` crate is not used anywhere in code and can safely be removed

Remove superfluous dependency to chrono

---

.github/workflows/ci.yml
reqwest-tracing/src/reqwest_otel_span_builder.rs

[user-agent issue](https://github.com/TrueLayer/reqwest-middleware/pull/167/files/4a2b3f335e9ea2f080f0d13ee782b830607b1f60#r1689595502)

fix: user-agent

---

reqwest-retry/src/middleware.rs

```
error: doc list item missing indentation
Error:   --> reqwest-retry/src/middleware.rs:62:4
|
62 | /// `Body`'s `From<String>` or `From<Bytes>` implementations.
|    ^
|
= help: if this is supposed to be its own paragraph, add a blank line
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_lazy_continuation
= note: `-D clippy::doc-lazy-continuation` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::doc_lazy_continuation)]`
help: indent this line
|
62 | ///   `Body`'s `From<String>` or `From<Bytes>` implementations.
|     ++
error: doc list item missing indentation
Error:   --> reqwest-retry/src/middleware.rs:65:4
|
65 | /// source directly, avoiding the issue of streaming requests not being clonable.
|    ^ …
```

fix(lint): `clippy::doc_lazy_continuation`

---

reqwest-middleware/Cargo.toml

This is helpful for [this test](https://github.com/TrueLayer/reqwest-middleware/blob/c90089ebd4cecf7cfb7d84d6664a993983682ce1/reqwest-middleware/src/lib.rs#L8).
This enables tests to pass when running `cargo test --no-default-features`.

fix(test): enable `rustls-tls` for tests

---

.github/workflows/ci.yml

waiting on #175 & #176 to fix issues with the build
Recently a [change was introduced that did not compile](https://github.com/TrueLayer/reqwest-middleware/pull/167/files/4a2b3f335e9ea2f080f0d13ee782b830607b1f60#r1689595502) #167.
This was not caught by our CI becuase the feature was not enabled when building in CI.
This change ensures that every possible feature combination is attempted when running tests and clippy in CI. This adds up to 50 attempts for all of our features accross the three crates in this repo. This doesn't take too long since they share build cache.

ci: use `cargo hack` feature powerset in CI

---

.github/workflows/ci.yml
reqwest-tracing/Cargo.toml
reqwest-tracing/src/lib.rs
reqwest-tracing/src/middleware.rs
reqwest-tracing/src/otel.rs

Updates and hopefully fixes #168 
Building doesn't seem to work with `--all-features` but looking at it I don't think it ever worked with `deprecated_attributes`.
Feel free to just take the code and put it into the original PR or merge this.

OpenTelemetry 0.24 support

---

reqwest-middleware/src/client.rs

Adding `Default` derive macro to the `ClientWithMiddleware` type in order to have the same functionnality as base `reqwest::Client`

Added `Default` derive to allow for same functionality as base type

---

reqwest-tracing/CHANGELOG.md
reqwest-tracing/src/reqwest_otel_span_builder.rs

- The `SpanBackendWithUrl` middleware used to add the `http.url` attribute which was migrated to the `url.full` attribute as part of https://github.com/TrueLayer/reqwest-middleware/pull/141 but was not restored along with the other deprecated attributes when the `deprecated_attributes` feature was added so this change is to add it back in if that feature is enabled

fix: restore adding http.url as an attribute when deprecated_attributes feature is enabled

---

reqwest-middleware/Cargo.toml
reqwest-retry/Cargo.toml
reqwest-retry/src/middleware.rs

This pull request is trying to reduce dependencies by:
* removing not used deps or disabling default features
* making `tracing` dependency optional and using `log` instead
I hope I did cfg correctly as I'm doing it first time

Reduce dependencies in reqwest-retry

---

.github/PULL_REQUEST_TEMPLATE.md
reqwest-tracing/src/reqwest_otel_span_builder.rs

There were still some examples of the pre-v0.8 matchit syntax in the documentation. This PR updates them to the new syntax (and fixes a broken link in the GitHub pull request template).

Use new matchit syntax in documentation

---

CHANGELOG.md
reqwest-middleware/CHANGELOG.md
reqwest-middleware/src/error.rs
reqwest-retry/CHANGELOG.md
reqwest-retry/Cargo.toml
reqwest-retry/src/lib.rs
reqwest-retry/src/middleware.rs

As a user or developer, it is hard to tell whether a request failed randomly and was not retried, or whether it failed even with retries (e.g. https://github.com/astral-sh/uv/issues/3514). This PR adds the number of retries to the error chain if there were any retries. Example error chain:
```
error: Request failed after 3 retries
Caused by: error sending request for url (https://pypi.org/simple/tqdm/)
Caused by: client error (Connect)
Caused by: dns error: failed to lookup address information: Name or service not known
Caused by: failed to lookup address information: Name or service not known
```
I've also changed `request_middleware::Error` transparent to avoid being to verbose.

Add retries to error message

---

reqwest-tracing/CHANGELOG.md
reqwest-tracing/Cargo.toml
reqwest-tracing/src/lib.rs
reqwest-tracing/src/middleware.rs
reqwest-tracing/src/otel.rs

Note that https://github.com/open-telemetry/opentelemetry-rust/pull/2040 removed custom `writer` support from `opentelemetry-stdout`, so I didn't add that to the tests. Not sure what its purpose is since it only uses `std::io::sink()` anyways?

feat: Support OTel 0.25 & 0.26

---

.github/workflows/ci.yml

The current job takes too long and fails due to the exponential growth caused by new features introduced in https://github.com/TrueLayer/reqwest-middleware/pull/188

ci: split feature powerset job per crate

---

.github/workflows/ci.yml

Thanks for the suggestion @tl-eirik-albrigtsen
https://github.com/TrueLayer/reqwest-middleware/pull/192#discussion_r1804396867

ci: move away from deprecated `actions-rs/toolchain`

---

reqwest-middleware/CHANGELOG.md
reqwest-middleware/Cargo.toml
reqwest-retry/CHANGELOG.md
reqwest-retry/Cargo.toml
reqwest-tracing/CHANGELOG.md
reqwest-tracing/Cargo.toml

Hi,
I'd like to ask for new releases for the middleware crates: reqwest-middleware 0.4.0, reqwest-retry 0.7.0 and reqwest-tracing 0.5.4.
In [uv](https://github.com/astral-sh/uv), we're currently using a git dependency for https://github.com/TrueLayer/reqwest-middleware/pull/159, and we'd like to move to a crates.io dependency (https://github.com/astral-sh/uv/issues/8932).
I've bump reqwest-middleware and reqwest-retry according to being breaking changes in the error type, while requiring reqwest-middleware `>0.3.0, <0.5.0` in reqwest-retry and reqwest-tracing for minimal downstream disruption. I hope i got all the version number and changelog changes right.

Release new versions

---

reqwest-tracing/CHANGELOG.md
reqwest-tracing/Cargo.toml

Hello! Could we do a new release of reqwest-tracing to get the already-added opentelemetry 0.27 support out onto the published crate?

Release new version of reqwest-tracing

---

.github/workflows/ci.yml
reqwest-middleware/CHANGELOG.md
reqwest-middleware/src/client.rs

It is a followup for https://github.com/TrueLayer/reqwest-middleware/pull/162, but with CI step for wasm32 added. It runs only for `reqwest-middleware`, as other packages too have issues, which I was unable to investigate at the moment.

Fix wasm32 build

---

reqwest-middleware/CHANGELOG.md
reqwest-retry/Cargo.toml
reqwest-retry/src/middleware.rs

Swaps over to wasmtimer, an updated library from wasm-timer which is not maintained.
Closes #199 
See here for fork: https://github.com/google/tarpc/pull/388

Update wasm-timer to wasmtimer

---

reqwest-retry/tests/all/helpers/simple_server.rs
reqwest-tracing/src/otel.rs

Noticed these failing in #215. Seems better to address warnings from new version of `clippy` separately.
I just ran `cargo clippy --all-targets --all-features --fix`
(it might be a good idea to turn on CI for all PRs, that way the feedback loop is a bit tighter 😅 mostly a coincidence I checked if the PR had gotten any feedback as there's no notification from GH when CI runs. but if CI ran when I opened the PR, I would have acted 2 days ago)

chore: fix clippy warnings

---

reqwest-middleware/CHANGELOG.md
reqwest-middleware/Cargo.toml
reqwest-middleware/src/client.rs
reqwest-retry/src/retryable_strategy.rs
reqwest-tracing/CHANGELOG.md
reqwest-tracing/Cargo.toml

* Updates changelogs and versions so we can do a release
* Deprecated  `fetch_mode_no_cors `, as proposed in https://github.com/TrueLayer/reqwest-middleware/pull/225
* Making this change here as that PR has clippy issues and I'm unable to push to that branch. 
* Fix new clippy lints added in rust 1.86

Deprecate `fetch_mode_no_cors` and prepare for release

---

reqwest-middleware/CHANGELOG.md
reqwest-middleware/Cargo.toml
reqwest-retry/CHANGELOG.md
reqwest-retry/Cargo.toml
reqwest-retry/tests/all/helpers/simple_server.rs

What it says on the tin.
We've moved all our internal crates to thiserror 2.0, but we're still compiling 1.0.21 because of this crate. It would be nice if we could get away from it, if possible.

Update thiserror to 2.0
